CREATE TABLE MEMBER ( 
    MEM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(50) not NULL,
    NICKNAME VARCHAR(50) not NULL,
    TOKEN_ID VARCHAR(255) NOT NULL UNIQUE 
);


CREATE TABLE TODOLIST (
    TODO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) not NULL,
    CONTENT VARCHAR(4000) not NULL,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    COMPLETEYN BOOLEAN,
    MEM_ID INT,
    CONSTRAINT FK_MEMBER FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID)
);


CREATE TABLE CALENDAR (
    CAL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CALDATE TIMESTAMP not NULL,
    TODO_ID INT,   
    MEM_ID INT,
    CONSTRAINT FK_TODOLIST FOREIGN KEY (TODO_ID) REFERENCES TODOLIST(TODO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEM FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID)
);


select * from `member` m ; 
select * from todolist t ;   
select * from calendar c ;


